from .base import *
from .usuarios import *
from .areas import *
from .libros import *
from .equipos_computo import *
from .mobiliario import *
from .libros_virtuales import *
from .tesis import *
from .prestamos_libro import *
from .prestamos_area import *
from .prestamos_equipo_computo import *
from .multas import *