import os
import logging
import asyncio
from typing import Optional, Dict, Any

import httpx
from dotenv import load_dotenv
from fastapi import HTTPException

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Environment configuration (same style as database.py)
# ------------------------------------------------------------------
CHATBOT_HOST = os.getenv("CHATBOT_HOST", "localhost")
CHATBOT_PORT = os.getenv("CHATBOT_PORT", "8001")
CHATBOT_BASE_URL = f"http://{CHATBOT_HOST}:{CHATBOT_PORT}"
CHATBOT_TIMEOUT = float(os.getenv("CHATBOT_TIMEOUT", "15.0"))
CHATBOT_MAX_RETRIES = int(os.getenv("CHATBOT_MAX_RETRIES", "2"))

logger.info(f"🤖 Configurando cliente HTTP para asistente virtual en {CHATBOT_BASE_URL}")


# ------------------------------------------------------------------
# Async HTTP client (persistent for performance)
# ------------------------------------------------------------------
class ChatbotClient:
    """
    Async client for the virtual assistant microservice.
    Uses a persistent HTTP client to reuse connections.
    Handles session management and retries on rate limits.
    """
    def __init__(self):
        self.base_url = CHATBOT_BASE_URL
        self.timeout = CHATBOT_TIMEOUT
        self.max_retries = CHATBOT_MAX_RETRIES
        # Cliente persistente: se crea una sola vez y reutiliza conexiones
        # En lugar de crear uno nuevo por cada petición
        self.client = httpx.AsyncClient(timeout=self.timeout)
        print(f"🔧 Timeout configurado: {self.timeout}s")

    async def ask(
        self,
        question: str,
        session_id: str,
        user_tier: str = "comun"
    ) -> Dict[str, Any]:
        """
        Send a question to the chatbot and return the full response.

        Args:
            question: User's natural language query.
            session_id: Unique session ID (should be generated by main backend per user session).

        Returns:
            Dictionary containing 'answer', 'confidence', 'source', etc.

        Raises:
            HTTPException: On connection errors, timeouts, or rate limits.
        """
        url = f"{self.base_url}/chatbot/query"
        payload = {
            "question": question,
            "session_id": session_id
        }

        for attempt in range(self.max_retries + 1):
            try:
                # Usa el cliente persistente en lugar de crear uno nuevo
                response = await self.client.post(url, json=payload)
                
                # Handle rate limiting gracefully
                if response.status_code == 429:
                    retry_after = response.json().get("detail", {}).get("wait_seconds", 5)
                    logger.warning(
                        f"⚠️ Rate limit alcanzado para session {session_id}. "
                        f"Esperando {retry_after}s (intento {attempt+1})"
                    )
                    if attempt < self.max_retries:
                        await asyncio.sleep(retry_after)
                        continue
                    else:
                        raise HTTPException(
                            status_code=429,
                            detail="Demasiadas preguntas. Por favor espera unos segundos."
                        )
                
                # Raise for other HTTP errors
                response.raise_for_status()
                
                # Success
                data = response.json()
                logger.info(
                    f"✅ Respuesta de chatbot: "
                    f"confianza={data.get('confidence', 0):.2f}, "
                    f"fuente={data.get('source')}"
                )
                return data

            except httpx.TimeoutException:
                logger.error(f"⏱️ Timeout conectando al chatbot (intento {attempt+1})")
                if attempt == self.max_retries:
                    raise HTTPException(
                        status_code=504,
                        detail="El asistente virtual no responde a tiempo. Intenta más tarde."
                    )
                await asyncio.sleep(1.0)

            except httpx.HTTPStatusError as e:
                logger.error(f"❌ Error HTTP del chatbot: {e.response.status_code} - {e.response.text}")
                raise HTTPException(
                    status_code=502,
                    detail=f"Error en el asistente virtual: {e.response.status_code}"
                )

            except httpx.RequestError as e:
                logger.error(f"🌐 Error de red conectando al chatbot: {e}")
                if attempt == self.max_retries:
                    raise HTTPException(
                        status_code=503,
                        detail="No se pudo contactar al asistente virtual."
                    )
                await asyncio.sleep(1.0)

        raise HTTPException(status_code=500, detail="Error inesperado en cliente chatbot")

    async def health_check(self) -> bool:
        """Verify the chatbot microservice is reachable."""
        try:
            response = await self.client.get(f"{self.base_url}/chatbot/health")
            response.raise_for_status()
            return True
        except Exception as e:
            logger.error(f"❌ Health check fallido: {e}")
            return False

    async def close(self):
        """Cierra el cliente HTTP. Llamar al apagar la aplicación."""
        await self.client.aclose()


# ------------------------------------------------------------------
# Global client instance
# ------------------------------------------------------------------
chatbot_client = ChatbotClient()


# ------------------------------------------------------------------
# FastAPI Dependency for easy injection
# ------------------------------------------------------------------
async def get_chatbot() -> ChatbotClient:
    """
    Dependency that provides a configured ChatbotClient.
    Use in FastAPI route handlers.
    """
    return chatbot_client


# ------------------------------------------------------------------
# Helper: generate a stable session ID for a user
# ------------------------------------------------------------------
def generate_chatbot_session_id(user_id: int, session_token: str) -> str:
    """
    Create a deterministic session ID for the chatbot.
    This ensures conversation continuity across multiple requests from the same user session.
    
    Args:
        user_id: Database user ID.
        session_token: A unique token per browser session (e.g., from a cookie).
    
    Returns:
        String suitable as session_id for the chatbot.
    """
    import hashlib
    raw = f"{user_id}:{session_token}"
    return hashlib.sha256(raw.encode()).hexdigest()[:16]